# Generated by Django 5.2.6 on 2026-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('level', models.CharField(max_length=100)),
                ('time_commitment', models.CharField(max_length=100)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('roadmap', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
