# Generated by Django 5.2.6 on 2026-04-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoadmapRequest',
            new_name='NextStepRequest',
        ),
        migrations.RenameField(
            model_name='nextsteprequest',
            old_name='roadmap',
            new_name='next_step',
        ),
    ]
